# Generated by Django 6.0.1 on 2026-04-03 16:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenXe',
            fields=[
                ('ChuyenXeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NgayKhoiHanh', models.DateField(blank=True, null=True)),
                ('GioDi', models.TimeField(blank=True, null=True)),
                ('GioDen', models.TimeField(blank=True, null=True)),
                ('TrangThai', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('KhachHangID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('NgayDangKy', models.DateTimeField(auto_now_add=True)),
                ('AnhDaiDienURL', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loaixe',
            fields=[
                ('LoaixeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NgayCapNhatGia', models.DateField(blank=True, null=True)),
                ('SoCho', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('SoDoGheNgoiURL', models.CharField(blank=True, max_length=255, null=True)),
                ('GiaVe', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nhaxe',
            fields=[
                ('NhaxeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('NgayDangKy', models.DateTimeField(auto_now_add=True)),
                ('AnhDaiDienURL', models.CharField(blank=True, max_length=255, null=True)),
                ('DiaChiTruSo', models.TextField(blank=True, max_length=200, null=True)),
                ('SoDienThoai', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có 10 chữ số', regex='^0\\d{9,}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Taixe',
            fields=[
                ('TaixeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HinhAnhURL', models.CharField(blank=True, max_length=255, null=True)),
                ('SoBangLai', models.CharField(max_length=20, unique=True)),
                ('soCCCD', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='CCCD phải có đúng 12 chữ số', regex='^\\d{12}$')])),
                ('LoaiBangLai', models.CharField(blank=True, max_length=20, null=True)),
                ('NgayHetHanBangLai', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GheNgoi',
            fields=[
                ('gheID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('soGhe', models.CharField(blank=True, max_length=5, null=True)),
                ('trangThai', models.CharField(blank=True, max_length=20, null=True)),
                ('ChuyenXe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.chuyenxe')),
            ],
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='Taixe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.taixe'),
        ),
        migrations.CreateModel(
            name='TuyenXe',
            fields=[
                ('tuyenXeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tenTuyen', models.CharField(blank=True, max_length=500, null=True)),
                ('diemDi', models.CharField(default='Đà Nẵng', max_length=500)),
                ('diemDen', models.CharField(default='Huế', max_length=500)),
                ('QuangDuong', models.CharField(blank=True, max_length=100, null=True)),
                ('DiemTrungGian', models.CharField(blank=True, max_length=500, null=True)),
                ('nhaXe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.nhaxe')),
            ],
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='TuyenXe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.tuyenxe'),
        ),
        migrations.CreateModel(
            name='User_Authentication',
            fields=[
                ('UserID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenDangNhap', models.CharField(max_length=200, unique=True)),
                ('MatKhau', models.CharField(max_length=200)),
                ('Vaitro', models.CharField(max_length=20)),
                ('SoDienThoai', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có 10 chữ số', regex='^0\\d{9,}$')])),
                ('KhachHang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GETAPI.khachhang')),
                ('Nhaxe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GETAPI.nhaxe')),
            ],
        ),
        migrations.CreateModel(
            name='Ve',
            fields=[
                ('VeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SoDienThoai', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có 10 chữ số', regex='^0\\d{9,}$')])),
                ('NgayDat', models.DateTimeField(auto_now_add=True)),
                ('GiaVe', models.DecimalField(decimal_places=0, max_digits=10)),
                ('TrangThaiThanhToan', models.CharField(blank=True, max_length=20, null=True)),
                ('ChuyenXe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.chuyenxe')),
                ('Ghe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.ghengoi')),
                ('KhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('ThanhToanID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SoTien', models.DecimalField(decimal_places=4, max_digits=19)),
                ('PhuongThucTT', models.CharField(blank=True, max_length=20, null=True)),
                ('NgayThanhToan', models.DateTimeField(auto_now_add=True)),
                ('MaGiaoDich', models.CharField(blank=True, max_length=50, null=True)),
                ('Ve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.ve')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('DanhGiaID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Diemso', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Nhanxet', models.TextField(blank=True, max_length=500, null=True)),
                ('NgayDanhGia', models.DateTimeField(auto_now_add=True)),
                ('KhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.khachhang')),
                ('Ve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.ve')),
            ],
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('XeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TrangThai', models.CharField(blank=True, max_length=20, null=True)),
                ('SoGhe', models.IntegerField(blank=True, null=True)),
                ('BienSoXe', models.CharField(max_length=20, unique=True)),
                ('Loaixe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.loaixe')),
                ('Nhaxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.nhaxe')),
            ],
        ),
        migrations.AddField(
            model_name='chuyenxe',
            name='Xe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GETAPI.xe'),
        ),
        migrations.CreateModel(
            name='CHITIETLOAIXE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenLoaiXe', models.CharField(blank=True, max_length=50, null=True)),
                ('Tennhaxe', models.CharField(blank=True, max_length=200, null=True)),
                ('Loaixe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.loaixe')),
                ('Nhaxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.nhaxe')),
            ],
            options={
                'unique_together': {('Nhaxe', 'Loaixe')},
            },
        ),
        migrations.CreateModel(
            name='CHITIETTAIXE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(blank=True, max_length=200, null=True)),
                ('Tennhaxe', models.CharField(blank=True, max_length=200, null=True)),
                ('NgayBatDau', models.DateField()),
                ('NgayKetThuc', models.DateField()),
                ('Nhaxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.nhaxe')),
                ('Taixe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GETAPI.taixe')),
            ],
            options={
                'unique_together': {('Nhaxe', 'Taixe')},
            },
        ),
    ]
