# Generated by Django

from django.db import migrations
from datetime import date, time
from decimal import Decimal

def seed_data(apps, schema_editor):
    KhachHang = apps.get_model('GETAPI', 'KhachHang')
    Nhaxe = apps.get_model('GETAPI', 'Nhaxe')
    User_Authentication = apps.get_model('GETAPI', 'User_Authentication')
    Taixe = apps.get_model('GETAPI', 'Taixe')
    CHITIETTAIXE = apps.get_model('GETAPI', 'CHITIETTAIXE')
    Loaixe = apps.get_model('GETAPI', 'Loaixe')
    CHITIETLOAIXE = apps.get_model('GETAPI', 'CHITIETLOAIXE')
    Xe = apps.get_model('GETAPI', 'Xe')
    TuyenXe = apps.get_model('GETAPI', 'TuyenXe')
    ChuyenXe = apps.get_model('GETAPI', 'ChuyenXe')
    GheNgoi = apps.get_model('GETAPI', 'GheNgoi')
    Ve = apps.get_model('GETAPI', 'Ve')
    ThanhToan = apps.get_model('GETAPI', 'ThanhToan')
    DanhGia = apps.get_model('GETAPI', 'DanhGia')

    # 1. KhachHang
    kh1 = KhachHang.objects.create(KhachHangID="KH01", Email="kh1@gmail.com")
    kh2 = KhachHang.objects.create(KhachHangID="KH02", Email="kh2@gmail.com")

    # 2. Nhaxe
    nx1 = Nhaxe.objects.create(NhaxeID="NX01", Email="nx1@gmail.com", SoDienThoai="0901234567")
    nx2 = Nhaxe.objects.create(NhaxeID="NX02", Email="nx2@gmail.com", SoDienThoai="0987654321")

    # 3. User_Authentication
    User_Authentication.objects.create(UserID="U01", KhachHang=kh1, TenDangNhap="khachhang1", MatKhau="123", Vaitro="KhachHang", SoDienThoai="0911111111")
    User_Authentication.objects.create(UserID="U02", Nhaxe=nx1, TenDangNhap="nhaxe1", MatKhau="123", Vaitro="NhaXe", SoDienThoai="0922222222")
    
    # 4. Taixe
    tx1 = Taixe.objects.create(TaixeID="TX01", SoBangLai="BL01", soCCCD="123456789012")
    tx2 = Taixe.objects.create(TaixeID="TX02", SoBangLai="BL02", soCCCD="987654321098")

    # 5. CHITIETTAIXE
    CHITIETTAIXE.objects.create(Nhaxe=nx1, Taixe=tx1, HoTen="Tai xe 1")
    CHITIETTAIXE.objects.create(Nhaxe=nx2, Taixe=tx2, HoTen="Tai xe 2")

    # 6. Loaixe
    lx1 = Loaixe.objects.create(LoaixeID="LX01", SoCho=30, GiaVe=Decimal('150000.0000'))
    lx2 = Loaixe.objects.create(LoaixeID="LX02", SoCho=40, GiaVe=Decimal('200000.0000'))

    # 7. CHITIETLOAIXE
    CHITIETLOAIXE.objects.create(Nhaxe=nx1, Loaixe=lx1, TenLoaiXe="Xe giuong nam")
    CHITIETLOAIXE.objects.create(Nhaxe=nx2, Loaixe=lx2, TenLoaiXe="Xe ghe ngoi")

    # 8. Xe
    xe1 = Xe.objects.create(XeID="XE01", Nhaxe=nx1, Loaixe=lx1, BienSoXe="43A-12345")
    xe2 = Xe.objects.create(XeID="XE02", Nhaxe=nx2, Loaixe=lx2, BienSoXe="75B-67890")

    # 9. TuyenXe
    tuyen1 = TuyenXe.objects.create(tuyenXeID="T01", nhaXe=nx1, tenTuyen="Da Nang - Hue", diemDi="Da Nang", diemDen="Hue")
    tuyen2 = TuyenXe.objects.create(tuyenXeID="T02", nhaXe=nx2, tenTuyen="Hue - Da Nang", diemDi="Hue", diemDen="Da Nang")

    # 10. ChuyenXe
    cx1 = ChuyenXe.objects.create(ChuyenXeID="CX01", Xe=xe1, TuyenXe=tuyen1, Taixe=tx1, NgayKhoiHanh=date(2026, 4, 10), GioDi=time(7, 0), GioDen=time(10, 0))
    cx2 = ChuyenXe.objects.create(ChuyenXeID="CX02", Xe=xe2, TuyenXe=tuyen2, Taixe=tx2, NgayKhoiHanh=date(2026, 4, 11), GioDi=time(14, 0), GioDen=time(17, 0))

    # 11. GheNgoi
    ghe1 = GheNgoi.objects.create(gheID="G01", ChuyenXe=cx1, soGhe="A1", trangThai="Trong")
    ghe2 = GheNgoi.objects.create(gheID="G02", ChuyenXe=cx2, soGhe="A2", trangThai="Trong")

    # 12. Ve
    ve1 = Ve.objects.create(VeID="V01", KhachHang=kh1, ChuyenXe=cx1, Ghe=ghe1, SoDienThoai="0933333333", GiaVe=Decimal('150000.0000'), TrangThaiThanhToan="DaThanhToan")
    ve2 = Ve.objects.create(VeID="V02", KhachHang=kh2, ChuyenXe=cx2, Ghe=ghe2, SoDienThoai="0944444444", GiaVe=Decimal('200000.0000'), TrangThaiThanhToan="ChuaThanhToan")

    # 13. ThanhToan
    ThanhToan.objects.create(ThanhToanID="TT01", Ve=ve1, SoTien=Decimal('150000.0000'), PhuongThucTT="ChuyenKhoan")
    ThanhToan.objects.create(ThanhToanID="TT02", Ve=ve2, SoTien=Decimal('200000.0000'), PhuongThucTT="TienMat")

    # 14. DanhGia
    DanhGia.objects.create(DanhGiaID="DG01", Ve=ve1, KhachHang=kh1, Diemso=5, Nhanxet="Tot")
    DanhGia.objects.create(DanhGiaID="DG02", Ve=ve2, KhachHang=kh2, Diemso=4, Nhanxet="Kha")

def reverse_seed_data(apps, schema_editor):
    KhachHang = apps.get_model('GETAPI', 'KhachHang')
    Nhaxe = apps.get_model('GETAPI', 'Nhaxe')
    User_Authentication = apps.get_model('GETAPI', 'User_Authentication')
    Taixe = apps.get_model('GETAPI', 'Taixe')
    CHITIETTAIXE = apps.get_model('GETAPI', 'CHITIETTAIXE')
    Loaixe = apps.get_model('GETAPI', 'Loaixe')
    CHITIETLOAIXE = apps.get_model('GETAPI', 'CHITIETLOAIXE')
    Xe = apps.get_model('GETAPI', 'Xe')
    TuyenXe = apps.get_model('GETAPI', 'TuyenXe')
    ChuyenXe = apps.get_model('GETAPI', 'ChuyenXe')
    GheNgoi = apps.get_model('GETAPI', 'GheNgoi')
    Ve = apps.get_model('GETAPI', 'Ve')
    ThanhToan = apps.get_model('GETAPI', 'ThanhToan')
    DanhGia = apps.get_model('GETAPI', 'DanhGia')

    DanhGia.objects.all().delete()
    ThanhToan.objects.all().delete()
    Ve.objects.all().delete()
    GheNgoi.objects.all().delete()
    ChuyenXe.objects.all().delete()
    TuyenXe.objects.all().delete()
    Xe.objects.all().delete()
    CHITIETLOAIXE.objects.all().delete()
    Loaixe.objects.all().delete()
    CHITIETTAIXE.objects.all().delete()
    Taixe.objects.all().delete()
    User_Authentication.objects.all().delete()
    Nhaxe.objects.all().delete()
    KhachHang.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]