# Generated by Django 4.2.8 on 2026-04-20 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhaxe',
            name='Tennhaxe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chitiettaixe',
            name='NgayBatDau',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chitiettaixe',
            name='NgayKetThuc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='AnhDaiDienURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loaixe',
            name='GiaVe',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='nhaxe',
            name='AnhDaiDienURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nhaxe',
            name='SoDienThoai',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có ít nhất 10 số', regex='^0\\d{9,}$')]),
        ),
        migrations.AlterField(
            model_name='taixe',
            name='NgayHetHanBangLai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_authentication',
            name='MatKhau',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_authentication',
            name='SoDienThoai',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có ít nhất 10 số', regex='^0\\d{9,}$')]),
        ),
        migrations.AlterField(
            model_name='user_authentication',
            name='TenDangNhap',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ve',
            name='GiaVe',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ve',
            name='SoDienThoai',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và có ít nhất 10 số', regex='^0\\d{9,}$')]),
        ),
    ]
