# Generated by Django 4.2.8 on 2026-04-26 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chitietloaixe',
            options={'verbose_name': 'Chi tiết Loại xe', 'verbose_name_plural': 'Danh sách Chi tiết Loại xe'},
        ),
        migrations.AlterModelOptions(
            name='chitiettaixe',
            options={'verbose_name': 'Chi tiết Tài xế', 'verbose_name_plural': 'Danh sách Chi tiết Tài xế'},
        ),
        migrations.AlterModelOptions(
            name='chuyenxe',
            options={'verbose_name': 'Chuyến xe', 'verbose_name_plural': 'Danh sách Chuyến xe'},
        ),
        migrations.AlterModelOptions(
            name='danhgia',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Danh sách Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='ghengoi',
            options={'verbose_name': 'Ghế ngồi', 'verbose_name_plural': 'Danh sách Ghế ngồi'},
        ),
        migrations.AlterModelOptions(
            name='khachhang',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Danh sách Khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='loaixe',
            options={'verbose_name': 'Loại xe', 'verbose_name_plural': 'Danh sách Loại xe'},
        ),
        migrations.AlterModelOptions(
            name='nhaxe',
            options={'verbose_name': 'Nhà xe', 'verbose_name_plural': 'Danh sách Nhà xe'},
        ),
        migrations.AlterModelOptions(
            name='taixe',
            options={'verbose_name': 'Tài xế', 'verbose_name_plural': 'Danh sách Tài xế'},
        ),
        migrations.AlterModelOptions(
            name='thanhtoan',
            options={'verbose_name': 'Thanh toán', 'verbose_name_plural': 'Danh sách Thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='tuyenxe',
            options={'verbose_name': 'Tuyến xe', 'verbose_name_plural': 'Danh sách Tuyến xe'},
        ),
        migrations.AlterModelOptions(
            name='user_authentication',
            options={'verbose_name': 'Tài khoản User', 'verbose_name_plural': 'Danh sách Tài khoản User'},
        ),
        migrations.AlterModelOptions(
            name='ve',
            options={'verbose_name': 'Vé', 'verbose_name_plural': 'Danh sách Vé'},
        ),
        migrations.AlterModelOptions(
            name='xe',
            options={'verbose_name': 'Xe', 'verbose_name_plural': 'Danh sách Xe'},
        ),
    ]
