# Generated by Django 4.2.8 on 2026-04-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0002_nhaxe_tennhaxe_alter_chitiettaixe_ngaybatdau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='Ngaysinh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='Nguoidaidien',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
