# Generated by Django 4.2.8 on 2026-04-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0002_alter_chitietloaixe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuyenxe',
            name='TrangThai',
            field=models.CharField(blank=True, default='Chưa hoàn thành', max_length=50, null=True),
        ),
    ]
