# Generated by Django 6.0.1 on 2026-04-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_authentication',
            name='MatKhau',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_authentication',
            name='TenDangNhap',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
