# Generated by Django 6.0.2 on 2026-04-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0002_nhaxe_tennhaxe_alter_chitiettaixe_ngaybatdau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhaxe',
            name='TenNguoiDaiDien',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tuyenxe',
            name='ThoiGian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
