# Generated by Django 6.0.1 on 2026-04-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0003_alter_user_authentication_matkhau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_authentication',
            name='MatKhau',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_authentication',
            name='TenDangNhap',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
