# Generated by Django 4.2.8 on 2026-04-20 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0003_khachhang_ngaysinh_nhaxe_nguoidaidien'),
        ('GETAPI', '0003_nhaxe_tennguoidaidien_tuyenxe_thoigian'),
    ]

    operations = [
    ]
