# Generated by Django 4.2.8 on 2026-04-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0003_alter_chuyenxe_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaixe',
            name='GiaVe',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taixe',
            name='HinhAnhURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
