# Generated by Django 4.2.8 on 2026-04-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0004_alter_loaixe_giave_alter_taixe_hinhanhurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ve',
            old_name='GiaVe',
            new_name='TongTien',
        ),
        migrations.RemoveField(
            model_name='ve',
            name='Ghe',
        ),
    ]
