# Generated by Django 6.0.2 on 2026-04-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0004_merge_20260420_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhaxe',
            name='AnhDaiDienURL',
        ),
        migrations.RemoveField(
            model_name='nhaxe',
            name='Nguoidaidien',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='Hoten',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='AnhDaiDien',
            field=models.ImageField(blank=True, null=True, upload_to='nhaxe_avatars/'),
        ),
        migrations.AddField(
            model_name='tuyenxe',
            name='TrangThai',
            field=models.CharField(choices=[('Đang hoạt động', 'Đang hoạt động'), ('Bảo trì', 'Bảo trì'), ('Ngưng hoạt động', 'Ngưng hoạt động')], default='Đang hoạt động', max_length=50),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='ThoiGian',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
