# Generated by Django 4.2.8 on 2026-04-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0005_rename_giave_ve_tongtien_remove_ve_ghe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ve',
            name='TrangThai',
            field=models.CharField(choices=[('Đã đặt', 'Đã đặt'), ('Đã đi', 'Đã đi'), ('Đã hủy', 'Đã hủy')], default='Đã đặt', max_length=50),
        ),
    ]
