# Generated by Django 6.0.2 on 2026-04-20 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0005_remove_nhaxe_anhdaidienurl_remove_nhaxe_nguoidaidien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='Hoten',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='Ngaysinh',
        ),
    ]
