# Generated by Django 6.0.2 on 2026-04-27 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0006_ve_trangthai'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='Nhaxe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GETAPI.nhaxe'),
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nhaxe',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ve',
            name='NgayKetThuc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
