# Generated by Django 6.0.2 on 2026-04-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0006_remove_khachhang_hoten_remove_khachhang_ngaysinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuyenxe',
            name='ThoiGian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
