# Generated by Django 4.2.8 on 2026-04-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0006_ve_trangthai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghengoi',
            name='trangThai',
            field=models.CharField(choices=[('Còn trống', 'Còn trống'), ('Đã đặt', 'Đã đặt')], default='Còn trống', max_length=20),
        ),
        migrations.CreateModel(
            name='VeHuy',
            fields=[
                ('VeHuyID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SoDienThoai', models.CharField(blank=True, max_length=12, null=True)),
                ('NgayDat', models.DateTimeField(blank=True, null=True)),
                ('TongTien', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('TrangThaiThanhToan', models.CharField(choices=[('Chưa thanh toán', 'Chưa thanh toán'), ('Đã thanh toán', 'Đã thanh toán'), ('Đã hoàn tiền', 'Đã hoàn tiền')], default='Chưa thanh toán', max_length=20)),
                ('TrangThaiDanhGia', models.CharField(choices=[('Không có quyền', 'Không có quyền'), ('Chờ đánh giá', 'Chờ đánh giá'), ('Đã đánh giá', 'Đã đánh giá')], default='Không có quyền', max_length=50)),
                ('TrangThai', models.CharField(choices=[('Đã hủy', 'Đã hủy')], default='Đã hủy', max_length=50)),
                ('DiemDon', models.CharField(blank=True, max_length=500, null=True)),
                ('DiemTra', models.CharField(blank=True, max_length=500, null=True)),
                ('ThoiGianHuy', models.DateTimeField(auto_now_add=True)),
                ('DanhSachGhe', models.CharField(blank=True, max_length=500, null=True)),
                ('SoLuongGhe', models.IntegerField(blank=True, null=True)),
                ('ChuyenXe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GETAPI.chuyenxe')),
                ('KhachHang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GETAPI.khachhang')),
            ],
            options={
                'verbose_name': 'Vé hủy',
                'verbose_name_plural': 'Danh sách Vé hủy',
            },
        ),
    ]
