# Generated by Django 4.2.8 on 2026-04-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0007_alter_ghengoi_trangthai_vehuy'),
        ('GETAPI', '0007_danhgia_nhaxe_nhaxe_rating_count_nhaxe_rating_sum_and_more'),
    ]

    operations = [
    ]
