# Generated by Django 4.2.8 on 2026-04-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0007_alter_tuyenxe_thoigian'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='Ngaysinh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
