# Generated by Django 4.2.8 on 2026-04-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0008_khachhang_ngaysinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhaxe',
            name='AnhDaiDien',
            field=models.TextField(blank=True, null=True),
        ),
    ]
