# Generated by Django 4.2.8 on 2026-04-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0008_merge_20260427_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Authentication',
            new_name='UserAuthentication',
        ),
        migrations.RemoveField(
            model_name='nhaxe',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='nhaxe',
            name='rating_sum',
        ),
        migrations.RemoveField(
            model_name='ve',
            name='NgayKetThuc',
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='trangThai',
            field=models.CharField(choices=[('Còn trống', 'Còn trống'), ('Đang chọn', 'Đang chọn'), ('Đã đặt', 'Đã đặt')], default='Còn trống', max_length=20),
        ),
        migrations.AlterModelTable(
            name='userauthentication',
            table='GETAPI_user_authentication',
        ),
    ]
