# Generated by Django 4.2.8 on 2026-04-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0009_alter_nhaxe_anhdaidien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='Ngaysinh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
