# Generated by Django 4.2.8 on 2026-04-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0010_alter_khachhang_ngaysinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='Hovaten',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
