# Generated by Django 4.2.8 on 2026-04-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0011_khachhang_hovaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuyenxe',
            name='Taixe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GETAPI.taixe'),
        ),
    ]
