# Generated by Django 6.0.1 on 2026-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0012_alter_chuyenxe_taixe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ve',
            name='TrangThaiDanhGia',
            field=models.CharField(choices=[('Không có quyền', 'Không có quyền'), ('Chờ đánh giá', 'Chờ đánh giá'), ('Đã đánh giá', 'Đã đánh giá')], default='Không có quyền', max_length=50),
        ),
        migrations.AlterField(
            model_name='ve',
            name='TrangThaiThanhToan',
            field=models.CharField(choices=[('Chưa thanh toán', 'Chưa thanh toán'), ('Đã thanh toán', 'Đã thanh toán')], default='Chưa thanh toán', max_length=20),
        ),
    ]
