# Generated by Django 4.2.8 on 2026-04-25 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0013_ve_trangthaidanhgia_alter_ve_trangthaithanhtoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghengoi',
            name='Ve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghe_ngoi_ve', to='GETAPI.ve'),
        ),
        migrations.AddField(
            model_name='ve',
            name='DiemDon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ve',
            name='DiemTra',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ve',
            name='TrangThai',
            field=models.CharField(default='Hiện tại', max_length=50),
        ),
    ]
