# Generated by Django 4.2.8 on 2026-04-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0014_ghengoi_ve_ve_diemdon_ve_diemtra_ve_trangthai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ve',
            name='TrangThai',
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='trangThai',
            field=models.CharField(choices=[('Còn trống', 'Còn trống'), ('Đang chọn', 'Đang chọn'), ('Đã đặt', 'Đã đặt')], default='Còn trống', max_length=20),
        ),
    ]
