# Generated by Django 6.0.1 on 2026-04-25 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0014_ghengoi_ve_ve_diemdon_ve_diemtra_ve_trangthai'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHITIETKHACHHANG',
            fields=[
                ('KhachHang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GETAPI.khachhang')),
                ('Hovaten', models.CharField(blank=True, max_length=900, null=True)),
                ('AnhDaiDienURL', models.ImageField(blank=True, null=True, upload_to='khachhang_avatars/')),
                ('Ngaysinh', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='AnhDaiDienURL',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='Hovaten',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='Ngaysinh',
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='KhachHangID',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xe',
            name='TrangThai',
            field=models.CharField(choices=[('Đang hoạt động', 'Đang hoạt động'), ('Dừng hoạt động', 'Dừng hoạt động')], default='Đang hoạt động', max_length=50),
        ),
        migrations.AlterField(
            model_name='xe',
            name='XeID',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
