# Generated by Django 4.2.8 on 2026-04-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0015_chitietkhachhang_remove_khachhang_anhdaidienurl_and_more'),
        ('GETAPI', '0015_remove_ve_trangthai_alter_ghengoi_trangthai'),
    ]

    operations = [
    ]
