# Generated by Django 4.2.8 on 2026-04-26 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0016_merge_20260425_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhaxe',
            old_name='AnhDaiDien',
            new_name='AnhDaiDienURL',
        ),
        migrations.RemoveField(
            model_name='ghengoi',
            name='Ve',
        ),
        migrations.RemoveField(
            model_name='ve',
            name='DiemDon',
        ),
        migrations.RemoveField(
            model_name='ve',
            name='DiemTra',
        ),
        migrations.RemoveField(
            model_name='ve',
            name='TrangThaiDanhGia',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='AnhDaiDienURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='Taixe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GETAPI.taixe'),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='TrangThai',
            field=models.CharField(blank=True, default='Chưa hoàn thành', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='trangThai',
            field=models.CharField(choices=[('Trống', 'Trống'), ('Đã đặt', 'Đã đặt'), ('Đã thanh toán', 'Đã thanh toán')], default='Trống', max_length=20),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='KhachHangID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='TrangThai',
            field=models.CharField(choices=[('Đang hoạt động', 'Đang hoạt động'), ('Ngừng hoạt động', 'Ngừng hoạt động')], default='Đang hoạt động', max_length=50),
        ),
        migrations.AlterField(
            model_name='ve',
            name='TrangThaiThanhToan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xe',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xe',
            name='XeID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CHITIETKHACHHANG',
        ),
    ]
