# Generated by Django 4.2.8 on 2026-04-26 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GETAPI', '0017_rename_anhdaidien_nhaxe_anhdaidienurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhaxe',
            old_name='AnhDaiDienURL',
            new_name='AnhDaiDien',
        ),
        migrations.AddField(
            model_name='ghengoi',
            name='Ve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghe_ngoi_ve', to='GETAPI.ve'),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='Hovaten',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='Ngaysinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_authentication',
            name='Taixe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_user', to='GETAPI.taixe'),
        ),
        migrations.AddField(
            model_name='ve',
            name='DiemDon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ve',
            name='DiemTra',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ve',
            name='TrangThaiDanhGia',
            field=models.CharField(choices=[('Không có quyền', 'Không có quyền'), ('Chờ đánh giá', 'Chờ đánh giá'), ('Đã đánh giá', 'Đã đánh giá')], default='Không có quyền', max_length=50),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='Taixe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GETAPI.taixe'),
        ),
        migrations.AlterField(
            model_name='chuyenxe',
            name='TrangThai',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ghengoi',
            name='trangThai',
            field=models.CharField(choices=[('Còn trống', 'Còn trống'), ('Đang chọn', 'Đang chọn'), ('Đã đặt', 'Đã đặt')], default='Còn trống', max_length=20),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='KhachHangID',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tuyenxe',
            name='TrangThai',
            field=models.CharField(choices=[('Đang hoạt động', 'Đang hoạt động'), ('Bảo trì', 'Bảo trì'), ('Ngưng hoạt động', 'Ngưng hoạt động')], default='Đang hoạt động', max_length=50),
        ),
        migrations.AlterField(
            model_name='ve',
            name='TrangThaiThanhToan',
            field=models.CharField(choices=[('Chưa thanh toán', 'Chưa thanh toán'), ('Đã thanh toán', 'Đã thanh toán')], default='Chưa thanh toán', max_length=20),
        ),
    ]
